CREATE TABLE IF NOT EXISTS "USER"
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthdate date
);

CREATE TABLE IF NOT EXISTS FILM
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar NOT NULL,
    description   varchar(255),
    release_date  date    NOT NULL,
    duration      integer NOT NULL,
    mpa_rating_id bigint  NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIEND
(
    user_id   bigint  NOT NULL,
    friend_id bigint  NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES "USER" (id),
    FOREIGN KEY (friend_id) REFERENCES "USER" (id)
);

CREATE TABLE IF NOT EXISTS "LIKE"
(
    user_id bigint NOT NULL,
    film_id bigint NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES "USER" (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES FILM (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GENRE
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  bigint NOT NULL,
    genre_id bigint NOT NULL,
    FOREIGN KEY (film_id) REFERENCES FILM (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES GENRE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MPA_RATING
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar NOT NULL,
    description varchar
);

CREATE TABLE IF NOT EXISTS DIRECTOR (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_DIRECTOR (
    film_id BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES FILM(id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES DIRECTOR(id) ON DELETE CASCADE
);